### ISSUE TITLE
YOU COMMITED YOUR USERNAME AND PASSWORD FOR YOUR FTP SERVER

### ISSUE THREAD

**Issue by Prior99** [naviapis/dotfiles#1]
Please remove this whole repository as you committed your .config/filezilla/recentservers.xml File. Serveradress, Username and Password are stored plain-text in there. I recommend to remove this repository as soon as possible and change the respective passwords.

Please note that it is not unlikely that you could have been hacked.

**Comment by naviapis** [comment]
Thank you for the important information.
Fixed it.
